const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const MONTHS=['Jan','Feb','Mar','Apr','May','Jun'];
const state={client:'Client',period:'For the period ended',sheets:{},metrics:{income:0,gross:0,net:0,bank:0,ar:0,ap:0},months:[0,0,0,0,0,0],monthlyNet:[0,0,0,0,0,0],notes:''};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function money(n){return Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'})}
function num(v){if(typeof v==='number')return v;const raw=String(v??'').trim(),s=raw.replace(/[$,()]/g,''),n=parseFloat(s);return isFinite(n)?(raw.includes('(')?-n:n):0}
function findSheet(re){return Object.entries(state.sheets).find(([n])=>re.test(n))?.[1]||[]}
function findValue(rows,re){for(const r of rows){const label=String(r[0]??'').trim();if(re.test(label)){for(let i=r.length-1;i>0;i--){const v=num(r[i]);if(v||String(r[i]??'').match(/^0([.]0+)?$/))return v}}}return 0}
function findMonthly(rows,re){const out=[0,0,0,0,0,0];for(const r of rows){if(!re.test(String(r[0]??'').trim()))continue;const vals=r.slice(1).map(num).filter(v=>Number.isFinite(v));if(vals.length>=6)return vals.slice(0,6)}return out}
function analyze(){const pl=findSheet(/profit.*loss|p&l|income statement/i),bs=findSheet(/balance sheet/i),ar=findSheet(/a.?r.*aging/i),ap=findSheet(/a.?p.*aging/i),notes=findSheet(/notes?.*financial|financial.*notes/i);state.metrics.income=findValue(pl,/^total.*income$|^total income$|revenue total/i)||findValue(pl,/^income$/);state.metrics.gross=findValue(pl,/gross profit/i)||state.metrics.income;state.metrics.net=findValue(pl,/net income/i);state.metrics.bank=findValue(bs,/total.*bank accounts|cash.*bank|total cash/i);state.metrics.ar=findValue(bs,/total.*accounts receivable/i)||findValue(ar,/^total$/i);state.metrics.ap=findValue(bs,/total.*accounts payable/i)||findValue(ap,/^total$/i);state.months=findMonthly(pl,/^total.*income$|^total income$|revenue total/i);state.monthlyNet=findMonthly(pl,/net income/i);if(!state.notes&&notes.length)state.notes=notes.flat().filter(Boolean).join('\n');const first=[...Object.values(state.sheets)][0]||[];for(const r of first.slice(0,8)){const t=r.map(x=>String(x??'')).join(' '),m=t.match(/([A-Z][A-Z .,&'-]{4,}(?:INC\.?|LLC|LTD\.?))/i);if(m){state.client=m[1].trim();break}}for(const rows of Object.values(state.sheets)){for(const r of rows.slice(0,10)){const t=r.map(x=>String(x??'')).join(' '),m=t.match(/(?:As of|For the period ended|January\s*-\s*June|Jan\s*-\s*Jun)[^|]*/i);if(m){state.period=m[0].trim();break}}}render()}
function valueCell(v){const n=num(v),numeric=typeof v==='number'||/^\(?\$?[\d,.]+\)?$/.test(String(v??'').trim());return `<td class="${numeric&&n<0?'amount-neg':''}">${typeof v==='number'?money(v):String(v??'')}</td>`}
function reportRows(rows){if(!rows.length)return '<p>No matching worksheet was included in the uploaded workbook.</p>';return '<table>'+rows.slice(0,55).map(r=>{const total=/\btotal\b/i.test(String(r[0]??''));return `<tr class="${total?'total-row':''}">${r.slice(0,5).map(valueCell).join('')}</tr>`}).join('')+'</table>'}
function comparativeTable(){return `<table><tr><th>Month</th>${MONTHS.map(m=>`<th>${m}</th>`).join('')}</tr><tr><td>Revenue</td>${state.months.map(v=>`<td class="${v<0?'amount-neg':''}">${money(v)}</td>`).join('')}</tr><tr><td>Net Income</td>${state.monthlyNet.map(v=>`<td class="${v<0?'amount-neg':''}">${money(v)}</td>`).join('')}</tr></table>`}
function renderChart(){const vals=[...state.months,...state.monthlyNet],max=Math.max(...vals.map(v=>Math.abs(v)),1);$('#chart').innerHTML=MONTHS.map((mo,i)=>{const r=state.months[i]||0,n=state.monthlyNet[i]||0,rh=Math.max(2,Math.abs(r)/max*105),nh=Math.max(2,Math.abs(n)/max*105);return `<div class="barbox"><div class="plot"><div class="zero-line"></div><div title="Revenue ${money(r)}" class="bar revenue ${r<0?'negative':'positive'}" style="height:${rh}px"></div><div title="Net Income ${money(n)}" class="bar net ${n<0?'negative':'positive'}" style="height:${nh}px"></div></div><span>${mo}</span></div>`}).join('')}
function render(){const m=state.metrics;$('#clientLine').textContent=state.client+' • '+state.period;const items=[['Revenue / Income',m.income],['Gross Profit',m.gross],['Net Income',m.net],['Cash / Bank',m.bank],['A/R Total',m.ar],['A/P Total',m.ap]];$('#kpis').innerHTML=items.map(([l,v])=>`<div class="kpi"><small>${l}</small><strong class="${v<0?'neg':''}">${money(v)}</strong></div>`).join('');renderChart();$('#comparison').innerHTML=comparativeTable();const a=[];if(m.net<0)a.push(['Net loss for the period',money(m.net)]);if(m.ar>0)a.push(['Accounts Receivable requires review',money(m.ar)]);if(m.ap>0)a.push(['Accounts Payable requires review',money(m.ap)]);$('#alerts').innerHTML=a.map(x=>`<div class="alert"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('')||'<div class="alert"><b>No major alerts detected</b></div>';$('#coverClient').textContent=state.client;$('#coverPeriod').textContent=state.period;$('#rperiod').textContent=$('#plperiod').textContent=$('#bsperiod').textContent=$('#notesperiod').textContent=state.period;$('#rdash').innerHTML=items.map(([l,v])=>`<div class="dashrow"><span>${l}</span><b class="${v<0?'amount-neg':''}">${money(v)}</b></div>`).join('');$('#rcomparison').innerHTML=comparativeTable();$('#rpl').innerHTML=reportRows(findSheet(/profit.*loss|p&l|income statement/i));$('#rbs').innerHTML=reportRows(findSheet(/balance sheet/i));$('#notesText').value=state.notes;$('#reportNotes').textContent=state.notes||'No notes have been entered for this report.';renderEditor()}
function renderEditor(){const names=Object.keys(state.sheets);$('#sheetSelect').innerHTML=names.map(n=>`<option>${n}</option>`).join('');showSheet($('#sheetSelect').value||names[0])}
function showSheet(name){const rows=state.sheets[name]||[];$('#editTable').innerHTML=rows.slice(0,180).map((r,ri)=>`<tr class="${/\btotal\b/i.test(String(r[0]??''))?'total-row':''}">`+r.slice(0,14).map((v,ci)=>`<td class="${num(v)<0?'amount-neg':''}"><input data-row="${ri}" data-col="${ci}" value="${String(v??'').replace(/"/g,'&quot;')}"></td>`).join('')+'</tr>').join('');$$('#editTable input').forEach(i=>i.onchange=()=>state.sheets[name][+i.dataset.row][+i.dataset.col]=i.value)}
function downloadExcel(){if(!Object.keys(state.sheets).length)return alert('Upload a workbook first.');const wb=XLSX.utils.book_new();Object.entries(state.sheets).forEach(([name,rows])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(rows),name.slice(0,31)));if(state.notes){const ws=XLSX.utils.aoa_to_sheet([['Notes to Financial Statements'],[state.notes]]);XLSX.utils.book_append_sheet(wb,ws,'Management Notes')}XLSX.writeFile(wb,(state.client||'Client').replace(/[^a-z0-9]+/gi,'-')+'-Processed-Financials.xlsx');toast('Excel download started')}
async function saveReport(){const blob=UnisonPDF.create(state,findSheet),name=(state.client||'Client').replace(/[^a-z0-9]+/gi,'-')+'-Management-Report.pdf';if(await UnisonPDF.save(blob,name))toast('PDF saved/downloaded successfully')}
$$('.nav button').forEach(b=>b.onclick=()=>{$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.page).classList.add('active');$('#title').textContent=b.textContent});$$('[data-report]').forEach(b=>b.onclick=()=>{$$('.sheet').forEach(x=>x.classList.remove('active'));$('#r-'+b.dataset.report).classList.add('active')});$('#sheetSelect').onchange=e=>showSheet(e.target.value);$('#refresh').onclick=()=>{analyze();toast('Dashboard and report updated')};$('#saveNotes').onclick=()=>{state.notes=$('#notesText').value.trim();$('#reportNotes').textContent=state.notes||'No notes have been entered for this report.';toast('Financial notes updated')};$('#downloadExcel').onclick=downloadExcel;$('#downloadExcelData').onclick=downloadExcel;$('#file').onchange=e=>$('#fileStatus').textContent=e.target.files[0]?.name||'No file selected';$('#process').onclick=async()=>{const f=$('#file').files[0];if(!f)return alert('Select an Excel or CSV file first.');try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});state.sheets={};wb.SheetNames.forEach(n=>state.sheets[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:true,defval:''}));analyze();toast('Workbook processed successfully');$$('.nav button').find(b=>b.dataset.page==='dashboard').click()}catch(e){alert('Could not process workbook: '+e.message)}};$('#savePdf').onclick=saveReport;$('#saveTop').onclick=saveReport;$('#openPdf').onclick=()=>{const u=URL.createObjectURL(UnisonPDF.create(state,findSheet));window.open(u,'_blank');setTimeout(()=>URL.revokeObjectURL(u),120000)};render();