const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const state={sheets:{},active:'',metrics:{income:0,gross:0,net:0,bank:0,ar:0,ap:0},months:[0,0,0,0,0,0]};
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
window.goPage=function(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===id));$('#pageTitle').textContent=$(`.nav button[data-page="${id}"]`)?.textContent.trim()||'Dashboard';if(innerWidth<801)$('#sidebar').classList.remove('open')}
$$('.nav button').forEach(b=>b.onclick=()=>goPage(b.dataset.page));$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function findSheet(re){return Object.entries(state.sheets).find(([n])=>re.test(n))?.[1]||[]}
function num(v){if(typeof v==='number')return v;let s=String(v??'').trim(),n=parseFloat(s.replace(/[$,()]/g,''));return isFinite(n)?(s.includes('(')?-n:n):0}
function findValue(rows,re){for(const r of rows){if(re.test(String(r[0]??''))){for(let i=r.length-1;i>0;i--){let n=num(r[i]);if(n)return n}}}return 0}
function analyze(){let pl=findSheet(/profit.*loss|p&l|income statement/i),bs=findSheet(/balance sheet/i),ar=findSheet(/a.?r.*aging/i),ap=findSheet(/a.?p.*aging/i);state.metrics.income=findValue(pl,/total.*income|revenue/i);state.metrics.gross=findValue(pl,/gross profit/i)||state.metrics.income;state.metrics.net=findValue(pl,/net income/i);state.metrics.bank=findValue(bs,/bank|cash/i);state.metrics.ar=findValue(bs,/accounts receivable/i)||findValue(ar,/total/i);state.metrics.ap=findValue(bs,/accounts payable/i)||findValue(ap,/total/i);render()}
function render(){let m=state.metrics,items=[['Revenue / Income',m.income,'Processed P&L'],['Gross Profit',m.gross,'Gross margin'],['Net Income',m.net,m.net<0?'Net loss for period':'Net income'],['Cash / Bank',m.bank,'Balance Sheet'],['A/R Total',m.ar,'Receivables'],['A/P Total',m.ap,'Payables']];$('#kpiGrid').innerHTML=items.map(([l,v,s])=>`<div class="kpi"><div class="label">${l}</div><div class="value ${v<0?'neg':''}">${money(v)}</div><div class="sub">${s}</div></div>`).join('');$('#attention').innerHTML=(m.net<0?`<div class="alert"><div><b>Net loss for the period</b><small>${money(m.net)}</small></div><span class="sev">High</span></div>`:'')+(m.ar?`<div class="alert"><div><b>A/R requires review</b><small>${money(m.ar)}</small></div><span class="sev">Review</span></div>`:'')+(m.ap?`<div class="alert"><div><b>A/P requires review</b><small>${money(m.ap)}</small></div><span class="sev">Review</span></div>`:'')||'<div class="empty">No major alerts detected</div>';renderTables();renderEditor()}
function table(rows,editable=false){if(!rows.length)return '<div class="empty">No matching worksheet was included in the uploaded workbook.</div>';return `<div class="table-wrap"><table class="fin-table ${editable?'edit-table':''}">${rows.slice(0,180).map((r,ri)=>`<tr class="${/total/i.test(String(r[0]||''))?'total':''}">${r.slice(0,12).map((v,ci)=>`<td class="${num(v)<0?'neg':''}">${editable?`<input data-r="${ri}" data-c="${ci}" value="${String(v??'').replaceAll('"','&quot;')}">`:String(v??'')}</td>`).join('')}</tr>`).join('')}</table></div>`}
function renderTables(){$('#plView').innerHTML=table(findSheet(/profit.*loss|p&l|income statement/i));$('#bsView').innerHTML=table(findSheet(/balance sheet/i));$('#arView').innerHTML=table(findSheet(/a.?r.*aging/i));$('#apView').innerHTML=table(findSheet(/a.?p.*aging/i))}
function renderEditor(){let names=Object.keys(state.sheets);if(!state.active)state.active=names[0]||'';$('#sheetTabs').innerHTML=names.map(n=>`<button class="${n===state.active?'active':''}" data-s="${n}">${n}</button>`).join('');$('#editorTable').innerHTML=table(state.sheets[state.active]||[],true);$$('#sheetTabs button').forEach(b=>b.onclick=()=>{state.active=b.dataset.s;renderEditor()});$$('#editorTable input').forEach(i=>i.onchange=()=>{state.sheets[state.active][+i.dataset.r][+i.dataset.c]=i.value;analyze()})}
$('#fileInput').onchange=e=>$('#fileName').textContent=e.target.files[0]?.name||'No new file selected';$('#processBtn').onclick=async()=>{let f=$('#fileInput').files[0];if(!f)return alert('Select a workbook first.');if(typeof XLSX==='undefined')return alert('Excel library could not load.');let wb=XLSX.read(await f.arrayBuffer(),{type:'array'});state.sheets={};wb.SheetNames.forEach(n=>state.sheets[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:true,defval:''}));state.active=wb.SheetNames[0]||'';$('#loadedStatus').textContent=`${wb.SheetNames.length} sheets processed`;$('#clientLine').textContent=f.name;['s1','s2','s3'].forEach(id=>$('#'+id).classList.add('done'));analyze();goPage('dashboard');toast('Workbook processed')};
$('#downloadCsv').onclick=()=>{if(!state.active)return;let ws=XLSX.utils.aoa_to_sheet(state.sheets[state.active]);let csv=XLSX.utils.sheet_to_csv(ws),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=state.active+'.csv';a.click()};$('#addRow').onclick=()=>{if(state.active){state.sheets[state.active].push(['']);renderEditor()}};$('#resetData').onclick=()=>{state.sheets={};state.active='';analyze();toast('Data cleared')};
function pdf(){window.print()}$('#downloadPdfTop').onclick=pdf;$('#downloadPdf').onclick=pdf;$('#openPdf').onclick=pdf;
render();